/**
 * `@map-harness/spatial-viz` — the spatial visualization workbench contracts
 * and computations: the versioned StyleSpec/LegendSpec pair, the
 * classification and time-axis machinery, and the shared selection/export
 * vocabulary.
 *
 * @module @map-harness/spatial-viz
 */
export {
  DEFAULT_MISSING_COLOR,
  DEFAULT_MISSING_LABEL,
  DEFAULT_OVERFLOW_COLOR,
  MAX_VIZ_CLASSES,
  MIN_VIZ_CLASSES,
  VIZ_GRANULARITIES,
  VIZ_METHOD_VERSION,
  VIZ_SERIES_IDENTITIES,
  isHexColor,
  isTimezone,
  isTimestamp,
  legendOf,
  stableStringify,
  styleVersionOf,
  validateStyleSpec,
  vizDigestOf,
  type ChartBrush,
  type ExportFailure,
  type ExportFailureKind,
  type ExportLayerBinding,
  type ExportManifest,
  type LegendClassRow,
  type LegendRow,
  type LegendSpecialRow,
  type LegendSpec,
  type SelectionFilter,
  type SelectionFrame,
  type StyleSpec,
  type TimeBinding,
  type VizClassification,
  type VizEncoding,
  type VizGranularity,
  type VizIssue,
  type VizMeasure,
  type VizSeriesIdentity,
} from './contract.ts'
export {
  SEQUENTIAL_RAMP,
  SIZE_MAX_PX,
  SIZE_MIN_PX,
  buildStyle,
  checkStyleInputs,
  classifyValue,
  computeBreaks,
  countClasses,
  measureValueOf,
  paletteOf,
  sizeForClass,
  unifyDomains,
  type BuiltStyle,
  type ClassifiedValue,
} from './classify.ts'
export {
  MAX_TIMELINE_FRAMES,
  TimelineError,
  axisAdvance,
  axisGoto,
  axisPause,
  axisPlay,
  axisStep,
  createTimeAxis,
  currentFrame,
  formatFrameLabel,
  framesOf,
  type TimeAxisState,
  type TimelineErrorCode,
  type TimelineFrame,
} from './timeline.ts'
export {
  MAX_ATTRIBUTE_ROWS,
  attributeRowsOf,
  dataRefOf,
  exportManifestOf,
  featureIdOf,
  filterRevisionOf,
  histogramOf,
  manifestDigestOf,
  selectFeatureIds,
  selectionFilterOf,
  type AttributeRow,
  type ExportInput,
  type HistogramBin,
  type SelectionInput,
  type WorkbenchFeature,
} from './linked.ts'
export {
  aggregateGridFeatures,
  createGridAggregator,
  GridAggregateFailure,
  type GridAggregateError,
  type GridAggregateParams,
  type GridAggregateResult,
  type GridCellFeature,
  type GridMeasure,
} from './aggregate.ts'
export {
  createFeatureCollectionScanner,
  scanFeatureCollectionChunks,
  StreamScanFailure,
  type ScanLimits,
  type ScannedFeature,
  type StreamScanError,
} from './stream.ts'
