/**
 * `@map-harness/spatial-accessibility` — the P1 accessibility layer: the
 * versioned `AccessibilitySpec` method contract with study/retrieval/support
 * extents and time windows, the controlled road-network/LBS provider (default
 * source) plus the opt-in Amap, Tianditu, and Mapbox vendor adapters behind a
 * validated Config choice and a user-held key, the durable
 * run_submit/get/cancel store with
 * service-adjudicated cancel and completion, population-weighted network
 * coverage, and the fixed-candidate comparison. The host face mounts through
 * the map-web profile patch; the model surface is the ordinary MCP run tools
 * map-tools registers.
 *
 * @module @map-harness/spatial-accessibility
 */
export {
  ACCESSIBILITY_METHOD_VERSION,
  BOUNDARY_RULE,
  MAX_CANDIDATES,
  MAX_IMPEDANCE_MINUTES,
  TIME_SLICE_IDS,
  newRunId,
  runOperationRefOf,
  sha256Hex,
  specDigestOf,
  straightLineExploration,
  usableAsNetworkEvidence,
  validateAccessibilitySpec,
  type AccessibilitySpec,
  type AnalysisSupportExtent,
  type BarrierSegment,
  type CapacityRule,
  type CandidateFacility,
  type CandidateOption,
  type ComparisonWeights,
  type EntrancePoint,
  type ExtentBox,
  type Impedance,
  type LonLat,
  type ObservationWindow,
  type RetrievalExtent,
  type RunId,
  type RunOperationRef,
  type SpecIssue,
  type SpecIssueCode,
  type StudyArea,
  type TimeSliceId,
  type TrainingWindow,
  type TravelMode,
} from './contract.ts'
export {
  AccessibilityError,
  RunCancelled,
  type AccessibilityErrorCode,
} from './errors.ts'
export {
  CONTROLLED_NETWORK_ID,
  DEFAULT_MODE_SPEED_KMH,
  DEFAULT_SLICE_FACTOR,
  collectPois,
  createControlledNetworkProvider,
  type NetworkProvider,
  type NetworkProviderConfig,
  type NetworkNode,
  type PoiCollection,
  type PoiCoverage,
  type PoiPage,
  type ProviderFaultCode,
  type ProviderFaultRule,
  type ServiceArea,
} from './network.ts'
export {
  AMAP_BASE_URL,
  AMAP_CAPABILITY_DECLARATION,
  AMAP_MAX_LATTICE_NODES,
  AMAP_MAX_PAGE_SIZE,
  AMAP_MAX_ROUTE_NODES,
  AMAP_MIN_SPACING_DEG,
  AMAP_NETWORK_ID,
  AMAP_PAGE_WINDOW_ROWS,
  AMAP_PROVIDER_LIMITATIONS,
  DEFAULT_AMAP_API_KEY_ENV,
  DEFAULT_AMAP_TIMEOUT_MS,
  amapNetworkRefFor,
  classifyAmapInfocode,
  createAmapNetworkProvider,
  type AmapFetch,
  type AmapProviderConfig,
  type VendorCapabilityDeclaration,
} from './amap.ts'
export {
  BAIDU_BASE_URL,
  BAIDU_CAPABILITY_DECLARATION,
  BAIDU_MAX_LATTICE_NODES,
  BAIDU_MAX_PAGE_SIZE,
  BAIDU_MAX_ROUTE_NODES,
  BAIDU_MIN_SPACING_DEG,
  BAIDU_NETWORK_ID,
  BAIDU_PAGE_WINDOW_ROWS,
  BAIDU_PROVIDER_LIMITATIONS,
  DEFAULT_BAIDU_API_KEY_ENV,
  DEFAULT_BAIDU_TIMEOUT_MS,
  baiduNetworkRefFor,
  classifyBaiduFailure,
  createBaiduNetworkProvider,
  parseBaiduRoute,
  type BaiduCapabilityDeclaration,
  type BaiduFetch,
  type BaiduProviderConfig,
  type BaiduRouteResult,
} from './baidu.ts'
export {
  DEFAULT_TIANDITU_API_KEY_ENV,
  DEFAULT_TIANDITU_TIMEOUT_MS,
  TIANDITU_BASE_URL,
  TIANDITU_CAPABILITY_DECLARATION,
  TIANDITU_MAX_ROUTE_NODES,
  TIANDITU_NETWORK_ID,
  TIANDITU_PROVIDER_LIMITATIONS,
  TIANDITU_STYLE_AVOID_HIGHWAY,
  TIANDITU_STYLE_FASTEST,
  TIANDITU_STYLE_SHORTEST,
  TIANDITU_STYLE_WALK,
  classifyTiandituFailure,
  createTiandituNetworkProvider,
  parseDriveXml,
  readXmlText,
  tiandituNetworkRefFor,
  type TiandituFailureKind,
  type TiandituFetch,
  type TiandituProviderConfig,
} from './tianditu.ts'
export {
  DEFAULT_TENCENT_API_KEY_ENV,
  DEFAULT_TENCENT_MAP_KEY_ENV,
  DEFAULT_TENCENT_TIMEOUT_MS,
  TENCENT_BASE_URL,
  TENCENT_CAPABILITY_DECLARATION,
  TENCENT_MAX_LATTICE_NODES,
  TENCENT_MAX_PAGE_SIZE,
  TENCENT_MAX_ROUTE_NODES,
  TENCENT_MIN_SPACING_DEG,
  TENCENT_NETWORK_ID,
  TENCENT_PAGE_WINDOW_ROWS,
  TENCENT_PROVIDER_LIMITATIONS,
  classifyTencentFailure,
  createTencentNetworkProvider,
  decodeTencentPolyline,
  parseTencentRoute,
  tencentNetworkRefFor,
  type TencentCapabilityDeclaration,
  type TencentFetch,
  type TencentProviderConfig,
  type TencentRouteResult,
} from './tencent.ts'
export {
  DEFAULT_MAPBOX_ACCESS_TOKEN_ENV,
  DEFAULT_MAPBOX_TIMEOUT_MS,
  MAPBOX_BASE_URL,
  MAPBOX_CAPABILITY_DECLARATION,
  MAPBOX_ISOCHRONE_PER_MINUTE,
  MAPBOX_MAX_CONTOURS,
  MAPBOX_MAX_CONTOUR_MINUTES,
  MAPBOX_MAX_COORDINATES,
  MAPBOX_MAX_ROUTE_NODES,
  MAPBOX_MAX_URL_BYTES,
  MAPBOX_MIN_CONTOUR_MINUTES,
  MAPBOX_MIN_COORDINATES,
  MAPBOX_NETWORK_ID,
  MAPBOX_PROFILES,
  MAPBOX_PROVIDER_LIMITATIONS,
  classifyMapboxFailure,
  createMapboxNetworkProvider,
  mapboxNetworkRefFor,
  parseDirectionsRoute,
  parseIsochronePolygon,
  type MapboxFetch,
  type MapboxProviderConfig,
} from './mapbox.ts'
export {
  evaluateComparison,
  projectComparison,
  type ComparisonInput,
  type ComparisonOutcome,
  type ComparisonProjection,
  type OptionEvaluation,
  type ProjectionRefusal,
  type ProjectionResult,
} from './compare.ts'
export {
  MAX_FACILITIES,
  MAX_POPULATION_UNITS,
  computeCoverage,
  providerForSpec,
  type CoverageComputeInput,
  type CoverageDiagnostic,
  type CoverageEvidence,
  type FacilityPoint,
  type PopulationUnit,
} from './metrics.ts'
export {
  ACCESSIBILITY_RUN_SCHEMA_VERSION,
  AccessibilityRunService,
  isTerminalStatus,
  openRunStore,
  sweepOrphans,
  type AccessibilityRunRecord,
  type AccessibilityRunStatus,
  type AccessibilityRunStore,
  type RunCheckpoints,
  type RunCompute,
  type RunOutcome,
  type RunSubmitInput,
  type RunSubmitResult,
} from './runs.ts'
export {
  MAX_PENDING_RUN_CALLS,
  RUN_SUBMIT_TOOL_NAME,
  SPATIAL_ACCESSIBILITY_STATE_VERSION,
  initialSpatialAccessibilityState,
  spatialAccessibilityProjectionDefinition,
  type PendingRunCall,
  type SpatialAccessibilityProjectionState,
} from './projection.ts'
export {
  SPATIAL_ACCESSIBILITY_SERVICE,
  type RunInputData,
  type RunSubmitSpecInput,
  type SpatialAccessibilityService,
} from './service.ts'
export {
  CONFIGURED_NETWORK_IDS,
  apply,
  Config,
  inject,
  name,
  resolveNetworkSource,
  type AccessibilityPluginConfig,
  type NetworkSourcePlan,
} from './plugin.ts'
