/**
 * `@map-harness/spatial-decision` — the P3 spatial decision-models layer:
 * the versioned attribution/forecast/scenario method contracts, the
 * association and model-explanation computations that never claim causality,
 * the controlled effect estimator with balance/overlap/interference
 * diagnostics and honest claim levels, the forecast validation/fit/prediction
 * path with baselines, time-forward holdouts, spatial blocks, intervals,
 * drift, and out-of-domain states, and the constrained scenario comparison
 * and location allocation with explicit weights, infeasible candidates, and
 * weight sensitivity. The model surface is the eight ordinary MCP decision
 * tools map-tools registers; the computations stay a pure library over exact
 * catalog versions.
 *
 * @module @map-harness/spatial-decision
 */
export {
  BALANCE_SMD_LIMIT,
  DECISION_METHOD_VERSION,
  DEFAULT_HOLDOUT_STEPS,
  DEFAULT_INTERVAL_LEVEL,
  DEFAULT_SCENARIO_WEIGHTS,
  GRANULARITIES,
  INTERFERENCE_SHARE_LIMIT,
  INTERVAL_LEVELS,
  MAX_ANALYSIS_ROWS,
  MAX_BAND_METERS,
  MAX_CANDIDATES,
  MAX_COMBINATION_NODES,
  MAX_FACTORS,
  MAX_FORECAST_FEATURES,
  MAX_GROUPS,
  MAX_HOLDOUT_STEPS,
  MAX_HORIZON_STEPS,
  MAX_SITES,
  MIN_ANALYSIS_ROWS,
  MIN_HOLDOUT_STEPS,
  OVERLAP_SHARE_MIN,
  SENSITIVITY_MULTIPLIERS,
  decisionSpecDigestOf,
  validateAssociationSpec,
  validateEffectSpec,
  validateExplainSpec,
  validateForecastPredictSpec,
  validateForecastSpec,
  validateLocationAllocateSpec,
  validateScenarioCompareSpec,
  type AllocateSite,
  type AssociationSpec,
  type AttributionSpec,
  type ClaimLevel,
  type DecisionIssue,
  type DecisionIssueCode,
  type DecisionSpec,
  type DecisionStatus,
  type DemandGroup,
  type DowngradeReason,
  type EffectSpec,
  type ExplainSpec,
  type FeatureAvailability,
  type ForecastBaseline,
  type ForecastFeature,
  type ForecastModelFamily,
  type ForecastPredictSpec,
  type ForecastSpec,
  type Granularity,
  type IdentificationDesign,
  type IntervalLevel,
  type LocationAllocateSpec,
  type LocationAllocateMode,
  type NotApplicableReason,
  type ScenarioCandidate,
  type ScenarioCompareSpec,
  type ScenarioWeights,
  type TimeWindow,
} from './contract.ts'
export {
  DecisionError,
  type DecisionErrorCode,
} from './errors.ts'
export {
  averageRanks,
  betainc,
  invertMatrix,
  logGamma,
  normalQuantile,
  olsFit,
  pearson,
  solveLinear,
  spearman,
  tCdf,
  tQuantile,
  type OlsFit,
} from './linalg.ts'
export {
  assertPermutationBounds,
  VIF_COLLINEAR_LIMIT,
  computeAssociation,
  computeExplain,
  type AnalysisRow,
  type AssociationEvidence,
  type AssociationFactor,
  type DecisionEvidenceHead,
  type DecisionPublish,
  type ExplainEvidence,
  type ExplainVif,
  type RowAccounting,
} from './attribution.ts'
export {
  computeEffect,
  type DiDDetail,
  type EffectDiagnosticRow,
  type EffectEvidence,
  type EffectInterval,
  type InterferenceReport,
} from './causal.ts'
export {
  FEATURE_DRIFT_LIMIT,
  MIN_THRESHOLD_LEAF_SAMPLES,
  QUADRATIC_RIDGE_LAMBDA,
  binIndexOf,
  computeForecastFit,
  computeForecastPredict,
  computeForecastValidation,
  type ForecastBlockRow,
  type ForecastEnvelope,
  type ForecastFitEvidence,
  type ForecastMetric,
  type ForecastPredictionEvidence,
  type ForecastPredictionRow,
  type ForecastRow,
  type ForecastValidationEvidence,
  type FittedForecastModel,
} from './forecast.ts'
export {
  allocateLocations,
  compareScenarios,
  type AllocateDemandRow,
  type AllocateGroupRow,
  type AllocateSiteRow,
  type LocationAllocateEvidence,
  type ScenarioCompareEvidence,
  type ScenarioRankRow,
  type ScenarioSensitivityRow,
} from './optimize.ts'
