/**
 * The spatial performance capacity contract (`spatial-perf@2`): the fully
 * specified, versioned binding every benchmark run, sample, and budget check
 * in this package carries. The contract fixes four things before anything is
 * measured:
 *
 * - **The frozen workload** — the benchmark inputs (seed, layer counts,
 *   fixture sizes, repetition counts) generate deterministic fixtures whose
 *   content digest is pinned in {@link PERF_FIXTURE_DIGEST}; a workload whose
 *   generated bytes stop matching the pin refuses to run, so threshold
 *   recordings always compare identical work.
 * - **The segment vocabulary** — the closed set of measurement points the
 *   design's runtime-metrics section names (context assembly, MCP codec,
 *   compute, commit acceptance, flush durability, render/display derivation,
 *   scan, cancel settlement). Every sample carries a segment from this set
 *   plus bounded, enumerable labels; payload bytes never enter a label.
 * - **The budgets** — hard cumulative limits (session/meta/projection/display
 *   bytes, scan rows, wall time, concurrency slots, steps) checked BEFORE a
 *   final operation commits; a refusal names its code and leaves the previous
 *   state untouched. Estimated provider costs are a separate recorded type
 *   no admission function accepts.
 * - **The recorded thresholds** — measured results of
 *   {@link runPerfBenchmark} on the recorded environment (with the raw
 *   observed ranges in the constant's comment), not aspirations: the three
 *   throughput floors are calibrated ratios against the adjacent probe, the
 *   remaining seven gates stay absolute, and a different host re-records first.
 *
 * Validation accepts the raw JSON-shaped input a caller forwards and returns
 * typed issues instead of throwing, so a rejected workload or budget lists
 * every reason rather than the first.
 *
 * @module @map-harness/spatial-perf/contract
 */
import { createHash } from 'node:crypto'

/**
 * The method identity this package computes; a report citing another version
 * is refused. The version pins every rule this package ships: the frozen
 * workload catalog and its digest pin, the closed segment vocabulary with
 * bounded labels, the cumulative pre-commit budget admission model, the
 * fixed-workload benchmark, and the threshold/stability/trend report layout.
 */
export const PERF_METHOD_VERSION = 'spatial-perf@2'

// -- calibration vocabulary ---------------------------------------------------

/** The closed set of calibration probe sections in the v2 benchmark method. */
export const PERF_CALIBRATION_SECTIONS = ['compute-mix'] as const

/** One calibration probe section name. */
export type PerfCalibrationSection = typeof PERF_CALIBRATION_SECTIONS[number]

/** The frozen batch shape used to measure one calibration section. */
export interface PerfCalibrationSectionSpec {
  readonly section: PerfCalibrationSection
  readonly batchUnits: number
  readonly batches: number
}

/**
 * Frozen probe work: each unit performs JSON round-trip, bounded Map insertion
 * and insertion-order eviction, and periodic numeric sort/copy work. The
 * specification is a measurement constant; changing it requires threshold
 * re-recording because fixed per-batch costs change the units/s denominator.
 */
export const PERF_CALIBRATION_SPEC: readonly PerfCalibrationSectionSpec[] = [
  { section: 'compute-mix', batchUnits: 50_000, batches: 3 },
] as const

/** Digest of the frozen calibration work product, checked by the probe runner. */
export const PERF_CALIBRATION_WORK_DIGEST = '93a47d568e1447f88b56f31fc5d9e8b050c34107436b442f14ed178f078d75ea'

// -- segment vocabulary -------------------------------------------------------

/**
 * The closed measurement vocabulary. Each value maps to one named
 * measurement point of the runtime-metrics design:
 *
 * - `context` — assembling the request plane for one step: the tool-call
 *   envelope and its argument serialization.
 * - `mcp` — the codec segment: JSON encode/decode of one operation's request
 *   and structured result payload (the adapter plane's own cost).
 * - `compute` — the domain computation: fixture admission walks, turf
 *   operations, candidate validation, projection refolds.
 * - `commit` — the accepted-call ladder: the `tool/call` + successful
 *   `tool/result` appends whose fold is the serial commit segment, and the
 *   catalog's staging→digest→transaction publish ladder.
 * - `flush` — the durability checkpoint barrier (`ctx.sessions.flush`).
 * - `render` — the Node-side display derivation: the projection wire view
 *   generation and validation a browser tab consumes. Browser paint stays in
 *   the composition lane and is never claimed here.
 * - `scan` — bounded data movement: stored-byte reads and feature-ref
 *   listings the workload performs.
 * - `cancel` — cancel-request to worker quiescence: the real end cost of a
 *   cancelled scan (child exit, staging clean), never the client promise.
 */
export const PERF_SEGMENTS = [
  'context',
  'mcp',
  'compute',
  'commit',
  'flush',
  'render',
  'scan',
  'cancel',
] as const

/** One measurement segment name. */
export type PerfSegment = typeof PERF_SEGMENTS[number]

/** The outcomes one sample can carry; failures and degradations are sampled, never swallowed. */
export const PERF_OUTCOMES = ['succeeded', 'partial', 'degraded', 'failed', 'cancelled'] as const

/** One sample outcome. */
export type PerfOutcome = typeof PERF_OUTCOMES[number]

/** The bounded label keys a sample may carry; unknown keys refuse loudly. */
export const PERF_LABEL_KEYS = ['workload', 'stage', 'unit'] as const

/** One label key. */
export type PerfLabelKey = typeof PERF_LABEL_KEYS[number]

/** One sample's bounded labels: known keys, short string values, never payload content. */
export type PerfLabels = Partial<Record<PerfLabelKey, string>>

/** Maximum characters of one label value; anything longer is a misuse, not a truncation. */
export const MAX_LABEL_VALUE_CHARS = 64

// -- frozen workload ----------------------------------------------------------

/** The benchmark workload ids; the catalog is closed. */
export const PERF_WORKLOAD_IDS = [
  'locate-visibility',
  'parse-register',
  'spatial-op',
  'recovery-replay',
  'two-point-chain',
] as const

/** One benchmark workload id. */
export type PerfWorkloadId = typeof PERF_WORKLOAD_IDS[number]

/**
 * The frozen benchmark workload. Every value is fixed so two runs generate
 * byte-identical fixtures and measure the same work; only wall-clock and
 * memory numbers vary within their bands. The field meanings:
 *
 * - `seed` — the deterministic PRNG seed all fixtures derive from.
 * - `repetitions` — how many times each workload repeats inside one run;
 *   gates evaluate the median repetition and the stability check compares
 *   the repetition spread.
 * - `locateLayerCount` / `locateLayerFeatures` — layers folded through the
 *   real projection for the locate/visibility workload, features per layer.
 * - `parseFeatureCount` — Point features of the parse/register fixture.
 * - `spatialOpRepeats` — buffer+area operations per spatial-op repetition.
 * - `recoveryMutations` — accepted mutations the recovery workload replays.
 */
export interface PerfWorkload {
  readonly seed: number
  readonly repetitions: number
  readonly locateLayerCount: number
  readonly locateLayerFeatures: number
  readonly parseFeatureCount: number
  readonly spatialOpRepeats: number
  readonly recoveryMutations: number
}

/** Bounds the workload validation enforces (values keep one benchmark run inside a CI-sized budget). */
export const PERF_WORKLOAD_BOUNDS = {
  maxRepetitions: 5,
  maxLocateLayerCount: 32,
  maxLayerFeatures: 2_000,
  maxParseFeatureCount: 10_000,
  maxSpatialOpRepeats: 64,
  maxRecoveryMutations: 64,
} as const

/**
 * The frozen workload fixture. `repetitions: 3` gives every gate a median and
 * a spread; the layer count stays inside the container's 32-layer capacity so
 * every fold applies for real.
 */
export const PERF_WORKLOAD_FIXTURE: PerfWorkload = {
  seed: 20260925,
  repetitions: 3,
  locateLayerCount: 12,
  locateLayerFeatures: 200,
  parseFeatureCount: 4_000,
  spatialOpRepeats: 20,
  recoveryMutations: 24,
} as const

/**
 * The pinned content digest of the fixtures {@link PERF_WORKLOAD_FIXTURE}
 * generates (sha256 over the canonical fixture bytes, see
 * `perfFixturesOf`). The workload runner recomputes the digest before
 * every run and refuses a mismatch: a fixture change is a threshold
 * re-recording event, never a silent comparison against different bytes.
 */
export const PERF_FIXTURE_DIGEST =
  'ec6da366da2e200f55dd2c28e21dc3613be894107b8e39446ce0b7c4de7e82ae'

// -- budgets ------------------------------------------------------------------

/** The hard cumulative budget fields; every one is enforced before a final operation commits. */
export interface PerfHardBudgets {
  /** Cumulative serialized session-event bytes the measured plane may append. */
  readonly maxSessionBytes: number
  /** Cumulative serialized `meta.spatial` bytes the measured plane may append. */
  readonly maxMetaBytes: number
  /** Cumulative serialized projection-state bytes the measured plane may hold. */
  readonly maxProjectionBytes: number
  /** Cumulative serialized display-copy (wire view) bytes the measured plane may derive. */
  readonly maxDisplayBytes: number
  /** Rows scanned by one final operation before it must refuse. */
  readonly maxScanRows: number
  /** Wall-clock milliseconds one final operation may take before it must refuse. */
  readonly maxTimeMs: number
  /** Concurrent operations the measured plane may run at once. */
  readonly maxConcurrency: number
  /** Steps one analysis may consume before its next operation refuses. */
  readonly maxSteps: number
}

/** Bounds the budget validation enforces. */
export const PERF_BUDGET_BOUNDS = {
  minBytes: 1,
  maxBytes: 2 * 1024 * 1024 * 1024,
  minScanRows: 1,
  maxScanRows: 100_000_000,
  minTimeMs: 1,
  maxTimeMs: 24 * 60 * 60_000,
  minConcurrency: 1,
  maxConcurrency: 64,
  minSteps: 1,
  maxSteps: 100_000,
} as const

/**
 * The recorded deployment budgets every measured plane in this deployment
 * runs under. These are deployment-owned defaults a caller writes explicitly
 * (never hidden defaults inside the runtime); they cap what one measured
 * session can accumulate. The projection/display ceilings align with the map
 * container's own bounds; the session/meta ceilings cap the measured planes
 * of one benchmark or tool session well below the disk-scale values where
 * durability policy belongs to the storage layer.
 */
export const PERF_DEPLOYMENT_BUDGETS: PerfHardBudgets = {
  maxSessionBytes: 256 * 1024 * 1024,
  maxMetaBytes: 64 * 1024 * 1024,
  maxProjectionBytes: 64 * 1024 * 1024,
  maxDisplayBytes: 32 * 1024 * 1024,
  maxScanRows: 1_000_000,
  maxTimeMs: 60_000,
  maxConcurrency: 8,
  maxSteps: 200,
} as const

/**
 * One estimated (non-enforced) provider cost. Cost estimates NEVER pass
 * through budget admission — they are recorded on the report for humans and
 * stay type-separated from {@link PerfHardBudgets}, so an estimate can never
 * refuse an operation a hard budget admits.
 */
export interface PerfEstimatedCost {
  /** What kind of external cost this estimates. */
  readonly kind: 'model-tokens' | 'lbs-calls' | 'job-minutes' | 'egress-bytes'
  /** Estimated amount in the kind's natural unit. */
  readonly amount: number
}

// -- recorded thresholds ------------------------------------------------------

/** Three throughput floors expressed as target units per calibration unit. */
export interface PerfRatioThresholds {
  /** Minimum locate/visibility folds per calibration unit. */
  readonly minLocateFoldsPerProbeUnit: number
  /** Minimum parse/register features per calibration unit. */
  readonly minParseFeaturesPerProbeUnit: number
  /** Minimum spatial operations per calibration unit. */
  readonly minSpatialOpsPerProbeUnit: number
}

/** One benchmark gate's threshold. Floors are minimums (`>=`), ceilings maximums (`<=`). */
export interface PerfThresholds extends PerfRatioThresholds {
  /** Maximum wall-clock milliseconds for the cold projection refold. */
  readonly maxRecoveryReplayMs: number
  /** Maximum wall-clock milliseconds for the whole two-point chain. */
  readonly maxChainWallMs: number
  /** Maximum milliseconds from cancel request to worker quiescence. */
  readonly maxCancelQuiescenceMs: number
  /** Maximum milliseconds for the flush durability checkpoint barrier. */
  readonly maxFlushWaitMs: number
  /** Maximum milliseconds for the display (wire view) derivation. */
  readonly maxRenderDeriveMs: number
  /** Maximum coordinating-process heap growth across one benchmark run, bytes. */
  readonly maxHeapGrowthBytes: number
  /** Maximum max/min ratio across repetitions of one workload's key metric. */
  readonly maxRepetitionSpreadRatio: number
}

/**
 * The environment the recorded thresholds were measured on; a different host
 * re-records before comparing. The ArcGIS JS API and the model id are
 * deployment inputs this keyless Node benchmark plane never loads — they are
 * recorded as declarations, not measurements.
 */
export const PERF_THRESHOLD_ENVIRONMENT =
  'darwin arm64 (Apple Silicon), node v25.2.1, one process plus real session/catalog stores on the local disk, worker-cancel leg spawns child processes, no container CPU limits'

/**
 * The v2 thresholds for {@link PERF_WORKLOAD_FIXTURE} on
 * {@link PERF_THRESHOLD_ENVIRONMENT}. The ratio floors were recorded on
 * 2026-10-08 on this long-running host (darwin arm64, node v25.2.1; load
 * during the three diagnostic runs was approximately 26, 20, and 13 for the
 * one-, five-, and fifteen-minute averages). The three runs produced ratio
 * medians of locate 0.000122/0.000124/0.000132, parse 0.265/0.297/0.298,
 * and spatial-op 0.000417/0.000425/0.000396. The corresponding probe
 * readings (units/s, in workload/repetition order) were:
 *
 * - run 1: 687299, 696832, 703018; 670516, 672766, 693906; 678529,
 *   681150, 704269;
 * - run 2: 685800, 675083, 680821; 679413, 667766, 679447; 682089,
 *   684310, 674888;
 * - run 3: 663961, 678522, 672842; 685139, 686210, 694444; 674056,
 *   665829, 694797.
 *
 * The target/probe ratio offset was therefore workload-specific: locate and
 * spatial-op retained the CPU compensation in this sample, while parse's
 * storage/transaction segment produced the wider observed sensitivity; the
 * three parse ratios varied across the recorded band as shown above. The
 * busiest-run repetition spread values were 1.883×, 1.970×, and 1.951×.
 * Each floor is the smallest observed ratio divided by two, rounded down to
 * three significant digits: 0.0000610, 0.132, and 0.000198. The remaining
 * seven absolute gates retain their v1 recorded headroom and the historical
 * absolute throughput is stored separately in {@link PERF_ADVISORY_THROUGHPUT}.
 * These are measurements, not aspirations; a run that misses one fails loudly.
 */
export const PERF_RECORDED_THRESHOLDS: PerfThresholds = {
  minLocateFoldsPerProbeUnit: 0.0000610,
  minParseFeaturesPerProbeUnit: 0.132,
  minSpatialOpsPerProbeUnit: 0.000198,
  maxRecoveryReplayMs: 100,
  maxChainWallMs: 1_000,
  maxCancelQuiescenceMs: 5_000,
  maxFlushWaitMs: 100,
  maxRenderDeriveMs: 50,
  maxHeapGrowthBytes: 512 * 1024 * 1024,
  maxRepetitionSpreadRatio: 8,
} as const

/** A historical absolute-throughput band retained for trend and diagnostic output only. */
export interface PerfAdvisoryBand {
  readonly unit: string
  readonly recordedAt: string
  readonly environment: string
  readonly low: number
  readonly high: number
  readonly retiredFloor: number
}

/** Historical v1 absolute throughput; no advisory field participates in a gate. */
export const PERF_ADVISORY_THROUGHPUT = {
  locateFoldsPerSecond: {
    unit: 'folds/s', recordedAt: '2026-09-25', environment: PERF_THRESHOLD_ENVIRONMENT,
    low: 233, high: 245, retiredFloor: 60,
  },
  parseFeaturesPerSecond: {
    unit: 'features/s', recordedAt: '2026-09-25', environment: PERF_THRESHOLD_ENVIRONMENT,
    low: 203_079, high: 240_713, retiredFloor: 50_000,
  },
  spatialOpsPerSecond: {
    unit: 'ops/s', recordedAt: '2026-09-25', environment: PERF_THRESHOLD_ENVIRONMENT,
    low: 235, high: 320, retiredFloor: 60,
  },
} as const satisfies Readonly<Record<'locateFoldsPerSecond' | 'parseFeaturesPerSecond' | 'spatialOpsPerSecond', PerfAdvisoryBand>>

/** The one-to-one mapping from throughput gates to calibration work. */
export const PERF_CALIBRATION_PAIRS = [
  {
    gate: 'locate folds throughput',
    workload: 'locate-visibility',
    metric: 'folds/s',
    section: 'compute-mix',
    floorField: 'minLocateFoldsPerProbeUnit',
  },
  {
    gate: 'parse/register throughput',
    workload: 'parse-register',
    metric: 'features/s',
    section: 'compute-mix',
    floorField: 'minParseFeaturesPerProbeUnit',
  },
  {
    gate: 'spatial-op throughput',
    workload: 'spatial-op',
    metric: 'ops/s',
    section: 'compute-mix',
    floorField: 'minSpatialOpsPerProbeUnit',
  },
] as const satisfies readonly {
  readonly gate: string
  readonly workload: PerfWorkloadId
  readonly metric: 'folds/s' | 'features/s' | 'ops/s'
  readonly section: PerfCalibrationSection
  readonly floorField: keyof PerfRatioThresholds
}[]

// -- validation ---------------------------------------------------------------

/** One structural contract issue: which field, a stable code, and why. */
export interface PerfIssue {
  readonly field: string
  readonly code: PerfIssueCode
  readonly message: string
}

/** The stable validation codes a workload/budget rejection carries. */
export type PerfIssueCode =
  | 'workload-required'
  | 'workload-bounds'
  | 'budgets-required'
  | 'budgets-bounds'
  | 'segment-unknown'
  | 'label-key-unknown'
  | 'label-value-bound'
  | 'outcome-unknown'

/**
 * Validate one raw workload value (the frozen-input contract).
 * @param workload - the raw workload value.
 * @returns the issue list; empty means the workload may run.
 */
export function validatePerfWorkload(workload: unknown): PerfIssue[] {
  const issues: PerfIssue[] = []
  if (typeof workload !== 'object' || workload === null) {
    return [{ field: 'workload', code: 'workload-required', message: 'the workload must be an object' }]
  }
  const record = workload as Partial<PerfWorkload>
  intBound(issues, 'seed', record.seed, 0, 2 ** 31 - 1, 'workload-bounds')
  intBound(issues, 'repetitions', record.repetitions, 1, PERF_WORKLOAD_BOUNDS.maxRepetitions, 'workload-bounds')
  intBound(issues, 'locateLayerCount', record.locateLayerCount, 1, PERF_WORKLOAD_BOUNDS.maxLocateLayerCount, 'workload-bounds')
  intBound(issues, 'locateLayerFeatures', record.locateLayerFeatures, 1, PERF_WORKLOAD_BOUNDS.maxLayerFeatures, 'workload-bounds')
  intBound(issues, 'parseFeatureCount', record.parseFeatureCount, 1, PERF_WORKLOAD_BOUNDS.maxParseFeatureCount, 'workload-bounds')
  intBound(issues, 'spatialOpRepeats', record.spatialOpRepeats, 1, PERF_WORKLOAD_BOUNDS.maxSpatialOpRepeats, 'workload-bounds')
  intBound(issues, 'recoveryMutations', record.recoveryMutations, 1, PERF_WORKLOAD_BOUNDS.maxRecoveryMutations, 'workload-bounds')
  return issues
}

/**
 * Validate one raw budgets value.
 * @param budgets - the raw budgets value.
 * @returns the issue list; empty means the budgets may run.
 */
export function validatePerfBudgets(budgets: unknown): PerfIssue[] {
  const issues: PerfIssue[] = []
  if (typeof budgets !== 'object' || budgets === null) {
    return [{ field: 'budgets', code: 'budgets-required', message: 'the budgets must be an object' }]
  }
  const record = budgets as Partial<PerfHardBudgets>
  byteBound(issues, 'maxSessionBytes', record.maxSessionBytes)
  byteBound(issues, 'maxMetaBytes', record.maxMetaBytes)
  byteBound(issues, 'maxProjectionBytes', record.maxProjectionBytes)
  byteBound(issues, 'maxDisplayBytes', record.maxDisplayBytes)
  intBound(issues, 'maxScanRows', record.maxScanRows, PERF_BUDGET_BOUNDS.minScanRows, PERF_BUDGET_BOUNDS.maxScanRows, 'budgets-bounds')
  intBound(issues, 'maxTimeMs', record.maxTimeMs, PERF_BUDGET_BOUNDS.minTimeMs, PERF_BUDGET_BOUNDS.maxTimeMs, 'budgets-bounds')
  intBound(issues, 'maxConcurrency', record.maxConcurrency, PERF_BUDGET_BOUNDS.minConcurrency, PERF_BUDGET_BOUNDS.maxConcurrency, 'budgets-bounds')
  intBound(issues, 'maxSteps', record.maxSteps, PERF_BUDGET_BOUNDS.minSteps, PERF_BUDGET_BOUNDS.maxSteps, 'budgets-bounds')
  return issues
}

/** Validate one byte-carrying budget field. */
function byteBound(issues: PerfIssue[], field: string, value: unknown): void {
  intBound(issues, field, value, PERF_BUDGET_BOUNDS.minBytes, PERF_BUDGET_BOUNDS.maxBytes, 'budgets-bounds')
}

/** Validate one numeric integer field against an inclusive bound, recording one issue per violation. */
function intBound(issues: PerfIssue[], field: string, value: unknown, min: number, max: number, code: PerfIssueCode): void {
  if (typeof value !== 'number' || !Number.isInteger(value) || value < min || value > max) {
    issues.push({ field, code, message: `${field} must be an integer in [${min}, ${max}]` })
  }
}

/**
 * The canonical digest of one plain-JSON value — the identity a report or
 * baseline pins.
 * @param value - the value to digest.
 * @returns a sha256 hex digest of the canonical JSON form.
 */
export function perfDigestOf(value: unknown): string {
  return createHash('sha256').update(JSON.stringify(value) ?? 'null', 'utf8').digest('hex')
}

/** Render one issue list the way every refusal message names its reasons. */
export function renderPerfIssues(issues: readonly PerfIssue[]): string {
  return issues.map(issue => `${issue.field} (${issue.code})`).join('; ')
}
