/**
 * The frozen fixture generation: every benchmark input derives from the
 * workload's fixed seed through integer-only deterministic math, so two runs
 * on any machine produce byte-identical fixtures. The generation is a pure
 * function of the workload — no clock, no randomness source, no environment
 * reads — and its canonical content digest is pinned in the contract
 * (`PERF_FIXTURE_DIGEST`); the runner re-derives and refuses a mismatch so
 * thresholds always compare identical bytes.
 *
 * @module @map-harness/spatial-perf/fixtures
 */
import { createHash } from 'node:crypto'
import { PERF_FIXTURE_DIGEST, type PerfWorkload } from './contract.ts'

/** One generated GeoJSON Point feature (fixed key order for canonical serialization). */
export interface PerfPointFeature {
  readonly type: 'Feature'
  readonly id: string
  readonly geometry: { readonly type: 'Point'; readonly coordinates: readonly [number, number] }
  readonly properties: { readonly value: number }
}

/** One generated GeoJSON FeatureCollection of point features. */
export interface PerfPointCollection {
  readonly type: 'FeatureCollection'
  readonly features: readonly PerfPointFeature[]
}

/** One generated polygon feature the spatial-op workload buffers. */
export interface PerfPolygonFeature {
  readonly type: 'Feature'
  readonly id: string
  readonly geometry: { readonly type: 'Polygon'; readonly coordinates: readonly [readonly (readonly [number, number])[]] }
  readonly properties: { readonly value: number }
}

/** The two-point chain fixture: the audit's required P0b scenario (the second point must be the one the chain selects). */
export interface PerfTwoPointFixture {
  readonly type: 'FeatureCollection'
  readonly features: readonly [
    { readonly type: 'Feature'; readonly id: 'alpha'; readonly geometry: { readonly type: 'Point'; readonly coordinates: readonly [number, number] }; readonly properties: { readonly name: 'first' } },
    { readonly type: 'Feature'; readonly id: 'beta'; readonly geometry: { readonly type: 'Point'; readonly coordinates: readonly [number, number] }; readonly properties: { readonly name: 'second' } },
  ]
}

/** Everything one benchmark run measures, all derived from one seed. */
export interface PerfFixtures {
  /** Layers for the locate/visibility workload (one FeatureCollection each). */
  readonly locateLayers: readonly PerfPointCollection[]
  /** The parse/register fixture bytes plus its feature count. */
  readonly parse: { readonly bytes: Uint8Array; readonly featureCount: number }
  /** The polygon the spatial-op workload buffers, plus its vertex count. */
  readonly spatialOp: { readonly polygon: PerfPolygonFeature }
  /** The two-point chain fixture bytes (the audit's required second-point scenario). */
  readonly twoPoint: { readonly bytes: Uint8Array; readonly fixture: PerfTwoPointFixture }
  /** The pinned digest the generated bytes hash to. */
  readonly digest: string
}

/**
 * A deterministic PRNG (mulberry32): integer state, pure arithmetic, no
 * platform randomness — the same seed yields the same sequence everywhere.
 * @param seed - the 32-bit seed.
 * @returns the next-value function producing floats in [0, 1).
 */
export function mulberry32(seed: number): () => number {
  let state = seed >>> 0
  return () => {
    state = (state + 0x6d2b79f5) | 0
    let t = Math.imul(state ^ (state >>> 15), 1 | state)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/** Round to six decimals (the display-exchange precision) without float dust. */
function round6(value: number): number {
  return Math.round(value * 1e6) / 1e6
}

/**
 * Generate one point collection: features laid out on a deterministic jitter
 * grid inside a fixed WGS84 window, ids and values from the sequence.
 * @param seed - the collection's stream seed.
 * @param count - the feature count.
 * @returns the collection.
 */
export function pointCollectionOf(seed: number, count: number): PerfPointCollection {
  const next = mulberry32(seed)
  const features: PerfPointFeature[] = []
  const side = Math.ceil(Math.sqrt(count))
  for (let index = 0; index < count; index++) {
    const column = index % side
    const row = Math.floor(index / side)
    const lon = round6(-10 + (20 * column) / side + next() * 0.01)
    const lat = round6(-8 + (16 * row) / side + next() * 0.01)
    features.push({
      type: 'Feature',
      id: `p-${index}`,
      geometry: { type: 'Point', coordinates: [lon, lat] },
      properties: { value: round6(next()) },
    })
  }
  return { type: 'FeatureCollection', features }
}

/** The regular 64-vertex polygon the spatial-op workload buffers (centered on [0, 0]). */
function spatialPolygonOf(): PerfPolygonFeature {
  const vertices: [number, number][] = []
  const verticesCount = 64
  for (let index = 0; index < verticesCount; index++) {
    const angle = (2 * Math.PI * index) / verticesCount
    const radius = index % 2 === 0 ? 0.01 : 0.007
    vertices.push([round6(Math.cos(angle) * radius), round6(Math.sin(angle) * radius)])
  }
  // Close the ring explicitly with the first vertex (GeoJSON linear ring rule).
  const ring = [...vertices, vertices[0] as [number, number]]
  return {
    type: 'Feature',
    id: 'op-polygon',
    geometry: { type: 'Polygon', coordinates: [ring] },
    properties: { value: 1 },
  }
}

/** The audit's two-point fixture: [0,0] "first" and [10,0] "second" — the chain must select the second. */
function twoPointFixtureOf(): PerfTwoPointFixture {
  return {
    type: 'FeatureCollection',
    features: [
      { type: 'Feature', id: 'alpha', geometry: { type: 'Point', coordinates: [0, 0] }, properties: { name: 'first' } },
      { type: 'Feature', id: 'beta', geometry: { type: 'Point', coordinates: [10, 0] }, properties: { name: 'second' } },
    ],
  }
}

/**
 * Generate every fixture one workload measures. Pure generation — no pin
 * check; callers that must compare against recorded thresholds use
 * {@link perfFixturesOf}, which refuses unpinned bytes.
 * @param workload - the workload to generate fixtures for.
 * @returns the fixtures with their content digest.
 */
export function generatePerfFixtures(workload: PerfWorkload): PerfFixtures {
  const locateLayers: PerfPointCollection[] = []
  for (let layer = 0; layer < workload.locateLayerCount; layer++) {
    locateLayers.push(pointCollectionOf(workload.seed + 1_000 + layer, workload.locateLayerFeatures))
  }
  const parseCollection = pointCollectionOf(workload.seed + 2_000, workload.parseFeatureCount)
  const parseBytes = Buffer.from(JSON.stringify(parseCollection), 'utf8')
  const spatialOp = { polygon: spatialPolygonOf() }
  const twoPointFixture = twoPointFixtureOf()
  const twoPointBytes = Buffer.from(JSON.stringify(twoPointFixture), 'utf8')

  const hash = createHash('sha256')
  for (const layer of locateLayers) {
    const bytes = Buffer.from(JSON.stringify(layer), 'utf8')
    hash.update(`${bytes.byteLength}:`)
    hash.update(bytes)
  }
  hash.update(`${parseBytes.byteLength}:`)
  hash.update(parseBytes)
  const polygonBytes = Buffer.from(JSON.stringify(spatialOp.polygon), 'utf8')
  hash.update(`${polygonBytes.byteLength}:`)
  hash.update(polygonBytes)
  hash.update(`${twoPointBytes.byteLength}:`)
  hash.update(twoPointBytes)
  const digest = hash.digest('hex')
  return {
    locateLayers,
    parse: { bytes: parseBytes, featureCount: workload.parseFeatureCount },
    spatialOp,
    twoPoint: { bytes: twoPointBytes, fixture: twoPointFixture },
    digest,
  }
}

/**
 * Generate the fixtures of a workload that will be compared against recorded
 * thresholds, and verify the canonical digest against the contract pin.
 * @param workload - the frozen workload (the recorded thresholds' workload).
 * @returns the fixtures with their digest.
 * @throws when the generated bytes stop matching the pinned
 *   `PERF_FIXTURE_DIGEST` — a fixture change is a re-recording event, never
 *   a silent comparison against different bytes.
 */
export function perfFixturesOf(workload: PerfWorkload): PerfFixtures {
  const fixtures = generatePerfFixtures(workload)
  if (fixtures.digest !== PERF_FIXTURE_DIGEST) {
    throw new Error(
      `perf fixtures no longer match the pinned digest: generated ${fixtures.digest}, pinned ${PERF_FIXTURE_DIGEST}. `
      + 'A fixture change is a threshold re-recording event: change the workload deliberately and re-record.',
    )
  }
  return fixtures
}
